version: 1.0.{build}

image:
- Visual Studio 2019

build:
  project: examples/csharp/Helloworld/Greeter.sln
  verbosity: normal

cache: # disbale build cache

matrix:
  fast_finish: false
  allow_failures:
    - NUGET_PACKAGES: "replace_to_cjk_char"
    - NUGET_PACKAGES: "C:\\ß\\packages"
    - NUGET_PACKAGES: "C:\\english with space\\packages"

environment:
  matrix:
    - NUGET_PACKAGES: "C:\\english_alphabet\\packages"
    - NUGET_PACKAGES: "replace_to_cjk_char"
    - NUGET_PACKAGES: "C:\\ß\\packages"
    - NUGET_PACKAGES: "C:\\english with space\\packages"

# Appveyor bug workaround
init:
  - ps: ./init.ps1

before_build:
  - cmd: echo %NUGET_PACKAGES%
  - cmd: nuget locals all -list
  - cmd: nuget restore examples/csharp/Helloworld/Greeter.sln
